### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by agilebharat** [Strikewood/woocommerce-first-atlantic-commerce#6]
( ! ) Parse error: syntax error, unexpected '[' in D:\wamp\www\woocommerce\wp-content\plugins\woocommerce-first-atlantic-commerce-master\includes\class-wc-gateway-fac.php on line 23

**Comment by einkoro** [comment]
What version of PHP are you on? Line 23 there is the array shorthand [] which should be supported since 5.4

**Comment by agilebharat** [comment]
yes,  i forgot this plugin worked in php version 5.4+
Now it's working.
